#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

show_ignored() {
  files=$(git ls-files -v | grep '^[[:lower:]]')

  if [ -n "${files}" ]; then
    echo '➜ The following files are ignored by git:'
    echo "${files}"
  fi

  # always return success for husky
  return 0
}

# shellcheck disable=SC2015
npx lint-staged && (show_ignored || true)
